FROM httpd:latest

LABEL version="Web de LatinCrack"

COPY assets /usr/local/apache2/htdocs/assets
COPY vendor /usr/local/apache2/htdocs/vendor
COPY prepros.config /usr/local/apache2/htdocs/
COPY prepros-6.config /usr/local/apache2/htdocs/
COPY index.html /usr/local/apache2/htdocs/
